# Generated by Django 6.0.1 on 2026-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo/'),
        ),
    ]
